<h1>Posts</h1>

<?php


/**
 * Output the result of calling the service operation.
 */
if (isset($response->Errors)) {
    foreach ($response->Errors as $error) {
        printf(
            "%s: %s\n%s\n\n",
            $error->SeverityCode === Enums\SeverityCodeType::C_ERROR ? 'Error' : 'Warning',
            $error->ShortMessage,
            $error->LongMessage
        );
    }
}
if ($response->Ack !== 'Failure') {
    printf("The official eBay time is: %s\n", $response->Timestamp->format('H:i (\G\M\T) \o\n l jS F Y'));
}
?>

<div class="row">

    <div class="col-md-8">

        <?php foreach($posts as $post): ?>

            <h3>
                <a href="#">
                    <?= $this->escapeHtml($post->getTitle()); ?>
                </a>

            </h3>
            Post ID: <?= $this->escapeHtml($post->getID()); ?>

            <p>
                Published: <?= $this->escapeHtml(date('jS \of F Y', strtotime($post->getDateCreated()))); ?>
                | Tags: <?= $this->escapeHtml($postManager->convertTagsToString($post)); ?>
            </p>


            <p>
                <?= $this->escapeHtml($post->getContent()); ?>
            </p>

        <?php endforeach; ?>

    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Post having tags</h3>
            </div>
            <div class="panel-body">

        <?php foreach($tagCloud as $tags): ?>
            <p><?= $this->escapeHtml($tags->getTitle()); ?></p>
        <?php endforeach; ?>

            </div>
        </div>
    </div>
</div>


